richardhj.simple_ajax.default:
    path: /SimpleAjax.php
    defaults:
        _controller: richardhj.simple_ajax.controller

richardhj.simple_ajax.frontend:
    path: /SimpleAjaxFrontend.php
    defaults:
        _controller: richardhj.simple_ajax.controller
